eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-user-hi
druid:
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 1234
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true

mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql