eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-department-hi
druid:
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 1234
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true

mybatis:
    type-aliases-package: com.kevin.cloud.*.api.model
    mapper-locations: classpath:mapper/*.xml

pagehelper:
    autoDialect: true
    closeConn: true
    offset-as-page-num: false